#!/usr/bin/env ruby

require 'optparse'
Dir["#{File.dirname(__FILE__)}/lib/**/*.rb"].each {|file| require file }

options = {}
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: kmlbo [options] kmlfile outputfile"
  opts.on("-s", "--simplify [EPSILON]", "Simplify the path using the Douglas Peucker algorithm (optionally using EPSILON as simplification factor)") do |s|
      options[:simplify] = true
      options[:epsilon] = s.to_f if s
    end
end

option_parser.parse!

kml_file = ARGV[0]
output_file = ARGV[1]

if (kml_file == nil || output_file == nil)
  puts "Missing required argument."
  puts  option_parser.banner
  exit 1
end

if options[:simplify]
  coordinates_array = KML.new(kml_file).simplify!(options[:epsilon]).to_a
else
  coordinates_array = KML.new(kml_file).to_a
end

File.open(output_file, "w+") do |file|
  file.write("PATH_COORDINATES = #{coordinates_array.to_s}")
end