#!/usr/bin/env ruby

require 'optparse'
Dir["#{File.dirname(__FILE__)}/lib/**/*.rb"].each {|file| require file }

options = {}
option_parser = OptionParser.new do |opts|
  opts.banner = "Usage: kmlbo [options] kmlfile outputfile"
  opts.on("-s", "--simplify [EPSILON]", "Simplify the path using the Douglas Peucker algorithm (optionally using EPSILON as simplification factor)") do |s|
    options[:simplify] = true
    options[:epsilon] = s.to_f if s
  end
  opts.on("-k", "--kml", "Emit kml instead of ruby") do |k|
    options[:kml] = true
  end
end

option_parser.parse!

kml_file = ARGV[0]
output_file = ARGV[1]

if (kml_file == nil || output_file == nil)
  puts "Missing required argument."
  puts  option_parser.banner
  exit 1
end

if options[:simplify]
  coordinates = KML.new(kml_file).simplify!(options[:epsilon])
else
  coordinates = KML.new(kml_file)
end

if options[:kml]
  File.open(output_file, "w+") do |file|
    file.write(coordinates.to_kml)
  end
else
  File.open(output_file, "w+") do |file|
    file.write("PATH_COORDINATES = #{coordinates.to_a.to_s}")
  end
end